version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:12.18
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dep-{{ checksum "yarn.lock" }}-
          - v1-dep-
      - run: yarn install
      - save_cache:
          key: v1-dep-{{ checksum "yarn.lock" }}
          paths:
          - ./node_modules
      - run: yarn jest

workflows:
  build_and_test:
    jobs:
      - build
